accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<str:username>/follow/', views.follow, name='follow'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:pk>/likes/', views.likes, name='likes'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')


class Comment(models.Model):
    content = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

movies/forms.py
from django import forms
from .models import Movie, Comment

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ('title', 'description',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)

movies/views.py
from django.shortcuts import render, redirect
from django.views.decorators.http import require_POST
from .models import Movie, Comment
from .forms import MovieForm, CommentForm

# Create your views here.
def index(request):
    movies = Movie.objects.all()
    context = {'movies':movies,}
    return render(request, 'movies/index.html', context)

def create(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            form = MovieForm(request.POST)
            if form.is_valid():
                movie = form.save(commit=False)
                movie.user = request.user
                movie.save()
                return redirect('movies:detail', movie.pk)
        else:
            form = MovieForm()
        context = {'form':form,}
        return render(request, 'movies/create.html', context)
    return redirect('accounts:login')

def detail(request, pk):
    movie = Movie.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = movie.comment_set.all()
    context = {
        'movie':movie,
        'comment_form':comment_form,
        'comments':comments,
        }
    return render(request, 'movies/detail.html', context)

def update(request, pk):
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=pk)
        if request.user == movie.user:
            if request.method == 'POST':
                form = MovieForm(request.POST, instance=movie)
                if form.is_valid():
                    form.save()
                    return redirect('movies:detail', movie.pk)
            else:
                form = MovieForm(instance=movie)
        else:
            return redirect('movies:index')
        context = {'form':form, 'movie':movie}
        return render(request, 'movies/update.html', context)
    return redirect('accounts:login')

@require_POST
def delete(request, pk):
    movie = Movie.objects.get(pk=pk)
    if request.user.is_authenticated:
        if request.user == movie.user:
            movie.delete()
            return redirect('movies:index')
    else:
        return redirect('movies:detail', movie.pk)
    
def comments_create(request, pk):
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=pk)
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.movie = movie
            comment.user = request.user
            comment.save()
        return redirect('movies:detail', movie.pk)
    return redirect('accounts:login')

def comments_delete(request, movie_pk, comment_pk):
    if request.user.is_authenticated:
        comment = Comment.objects.get(pk=comment_pk)
        if request.user == comment.user:
            comment.delete()
    return redirect('movies:detail', movie_pk)

@require_POST
def likes(request, pk):
    if request.user.is_authenticated:
        movie = Movie.objects.get(pk=pk)
        if movie.like_users.filter(pk=request.user.pk).exists():
            movie.like_users.remove(request.user)
        else:
            movie.like_users.add(request.user)
        return redirect('movies:index')
    return redirect('accounts:login')

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
<h1>CREATE</h1>
<hr>

<form action="{% url 'movies:create' %}" method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
<hr>
<a href="{% url 'movies:index' %}">BACK</a>


{% endblock content %}

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}
<h1>DETAIL</h1>
<hr>
<p>{{movie.title}}</p>
<p>{{movie.description}}</p>

{% if request.user.is_authenticated %}
{% if request.user == movie.user %}
<a href="{% url 'movies:update' movie.pk %}">UPDATE</a>
<form action="{% url 'movies:delete' movie.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="DELETE">
</form>
{% endif %}
{% endif %}

<a href="{% url 'movies:index' %}">BACK</a>
<hr>

<h4>댓글 목록</h4>
    {% if comments %}
    <p>총 {{comments|length}}개의 댓글이 있습니다.</p>
        <ul>
        {% for comment in comments %}
        <li>
            <span>{{comment.content}} - {{comment.user}}</span>
            {% if request.user == comment.user %}
            <form action="{% url 'movies:comments_delete' movie.pk comment.pk %}" method='POST'>
                {% csrf_token %}
                <input type="submit" value="DELETE">
            </form>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% else %}
    <p>댓글이 없습니다.</p>
    {% endif %}

<hr>
{% if request.user.is_authenticated %}
<form action="{% url 'movies:comments_create' movie.pk %}" method='POST'>
    {% csrf_token %}
    {{comment_form}}
    <input type="submit" value="제출">
</form>
{% else %}
    <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
{% endif %}

{% endblock content %}

movies/templates/movies/index.html
{% extends 'base.html' %}
{% block content %}
<h1>INDEX</h1>

{% if request.user.is_authenticated %}
<a href="{% url 'movies:create' %}">[CREATE]</a>
{% endif %}
<hr>

{% for movie in movies %}
    <br>
    <p>영화 제목 : <a href="{% url 'movies:detail' movie.pk %}">{{movie.title}}</a></p>
    <p>작성자 : <a href="{% url 'accounts:profile' movie.user.username %}">{{movie.user}}</a></p>
    <br>
    <form action="{% url 'movies:likes' movie.pk %}" method='POST'>
        {% csrf_token %}
        {% if request.user in movie.like_users.all %}
        <input type="submit" value="좋아요 취소">
        {% else %}
        <input type="submit" value="좋아요">
        {% endif %}
    </form>
    <br>
    <hr>
{% endfor %}

{% endblock content %}

movies/templates/movies/update.html
{% extends 'base.html' %}

{% block content %}
<h1>UPDATE</h1>
<hr>

<form action="{% url 'movies:update' movie.pk %}" method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>
<form action="{% url 'movies:update' movie.pk %}" method='GET'>
    <input type="submit" value="Reset">
</form>
<hr>
<a href="{% url 'movies:index' %}">BACK</a>

{% endblock content %}