accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('signup/', views.signup, name='signup'),
    path('delete/', views.delete, name='delete'),
    path('update/', views.update, name='update'),
    path('password/', views.password, name='password'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('<str:username>/follow/', views.follow, name='follow'),
]

movies/urls.py
from django.urls import path
from . import views

app_name = 'movies'
urlpatterns = [
    path('', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/update/', views.update, name='update'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),
    path('<int:movie_pk>/comments/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:pk>/likes/', views.likes, name='likes'),
]

mypjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    followings = models.ManyToManyField('self', symmetrical=False, related_name='followers')

movies/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Movie(models.Model):
    title = models.CharField(max_length=20)
    description = models.TextField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_movies')


class Comment(models.Model):
    content = models.CharField(max_length=100)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('first_name', 'last_name',)

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm, PasswordChangeForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.views.decorators.http import require_POST
from .forms import CustomUserCreationForm, CustomUserChangeForm
from django.contrib.auth import update_session_auth_hash, get_user_model

# Create your views here.
def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('movies:index')
    else:
        form = AuthenticationForm()
    context = {'form':form}
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('movies:index')

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('movies:index')
    else:
        form = CustomUserCreationForm()
    context = {'form':form}
    return render(request, 'accounts/signup.html', context)

def delete(request):
    request.user.delete()
    auth_logout(request)
    return redirect('movies:index')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('movies:index')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {'form':form}
    return render(request, 'accounts/update.html', context)

def password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('movies:index')
    else:
        form = PasswordChangeForm(request.user)
    context = {'form':form}
    return render(request, 'accounts/change_password.html', context)

def profile(request, username):
    User = get_user_model()
    person = User.objects.get(username=username)
    context = {
        'person':person,
    }
    return render(request, 'accounts/profile.html', context)

@require_POST
def follow(request, username):
    if request.user.is_authenticated:
        User = get_user_model()
        person = User.objects.get(username=username)
        if person != request.user:
            if person.followers.filter(pk=request.user.pk).exists():
                person.followers.remove(request.user)
            else:
                person.followers.add(request.user)
        return redirect('accounts:profile', person.username)
    return redirect('accounts:login')

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}

{% block content %}
<h1>비밀번호 변경</h1>
<form action="{% url 'accounts:password' %}" method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

<a href="{% url 'movies:index' %}">BACK</a>

{% endblock content %}

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
<h1>Login</h1>
<form action="{% url 'accounts:login' %}" method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

<a href="{% url 'movies:index' %}">BACK</a>

{% endblock content %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% block content %}
<h1>{{person.username}}'s Profile</h1>

<div>
    <p>팔로잉 : {{person.followings.all|length}}</p>
    <p>팔로워 : {{person.followers.all|length}}</p>

    {% if request.user != person %}
        <form action="{% url 'accounts:follow' person.username %}" method='POST'>
            {% csrf_token %}
            {% if request.user in person.followers.all %}
                <input type="submit" value="Unfollow">
            {% else %}
                <input type="submit" value="Follow">
            {% endif %}
        </form>
    {% endif %}
</div>

<hr>
<h4>{{person.username}}'s 영화</h4>
{% for movie in person.movie_set.all %}
    <p>{{movie.title}}</p>
{% endfor %}
<hr>

<h4>{{person.username}}'s 댓글</h4>
{% for comment in person.comment_set.all %}
    <p>{{comment.movie.title}} - {{comment.content}}</p>
{% endfor %}
<hr>

<h4>{{person.username}}'s 좋아요한 영화</h4>
{% for movie in person.like_movies.all %}
    <p>{{movie.title}}</p>
{% endfor %}
<hr>

<a href="{% url 'movies:index' %}">BACK</a>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}

{% block content %}
<h1>Signup</h1>
<form action="{% url 'accounts:signup' %}" method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

<a href="{% url 'movies:index' %}">BACK</a>

{% endblock content %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% block content %}
<h1>회원정보수정</h1>
<form action="{% url 'accounts:update' %}" method='POST'>
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

<a href="{% url 'movies:index' %}">BACK</a>

{% endblock content %}